In [1]:
import numpy as np

In [3]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
a.ndim

2

In [22]:
a.shape

(2, 7)

In [23]:
#select a specific row and return all columns
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [25]:
#select a specific columns and return all rows
a[:,3]

array([ 4, 11])

In [4]:
a.dtype

dtype('int64')

In [14]:
#number of individual bytes 
a.itemsize

8

In [15]:
#approach to get the total number of bytes
a.nbytes

112

In [16]:
#another approach to get the total number of bytes
a.size*a.itemsize

112

In [17]:
a.size

14

In [20]:
a[0, 1:-1:2]

array([2, 4, 6])

In [64]:
#3 dimentional
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [65]:
#Get specific elements,I want #4 of the first layer/set of elements
b[0,1,1]

4

In [66]:
b[0:,1,:1]
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [67]:
#replace certain elements in 2nd row 2nd column in each layers
b[:,1,1]=[10,11]
print(b)

[[[ 1  2]
  [ 3 10]]

 [[ 5  6]
  [ 7 11]]]


In [68]:
#replace all elements in 2nd row in each layers
b[:,1,:]=[10,11],[12,13]
print(b)

[[[ 1  2]
  [10 11]]

 [[ 5  6]
  [12 13]]]


In [69]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [1]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
print("Original a:\n", a)


Original a:
 [[1 2]
 [3 4]]


In [2]:
flat = a.flatten()
print("Flattened:", flat)

flat[0] = 99   # change first element
print("After modifying flat:")
print("flat:", flat)
print("a:\n", a)   # original stays same


Flattened: [1 2 3 4]
After modifying flat:
flat: [99  2  3  4]
a:
 [[1 2]
 [3 4]]


In [3]:
r = a.ravel()
print("Raveled:", r)

r[0] = 77   # change first element
print("After modifying r:")
print("r:", r)
print("a:\n", a)   # original also changed!


Raveled: [1 2 3 4]
After modifying r:
r: [77  2  3  4]
a:
 [[77  2]
 [ 3  4]]


In [4]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print(matrix[1:,  1:])

[[5 6]
 [8 9]]


In [10]:
#3 Dimensional array with 3 layers
z=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [11]:
print(z)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [29]:
#Start slicing from 2nd row,2nd col of the 2nd layer
z[1,1:,1:]

array([[11, 12]])